language: android

env:
  global:
   - ANDROID_API_LEVEL=27
   - EMULATOR_API_LEVEL=21
   - ANDROID_BUILD_TOOLS_VERSION=27.0.3
  matrix:
   - ANDROID_TARGET=android-24  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - sys-img-armeabi-v7a-$ANDROID_TARGET

jdk: oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-27"

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator